### ISSUE TITLE
hide auth headers on output of cy-api logs on the test runner

### ISSUE THREAD

**Issue by sravanireddyseelam** [bahmutov/cy-api#149]
On the output of request logs, we are also displaying the authentication  header values like username and password. Is there a way we can hide these headers and not display them?
How can i adjust the logs to select the type contents i want to be displayed on the test runner?

<img width="955" alt="Screen Shot 2022-01-31 at 5 10 40 PM" src="https://user-images.githubusercontent.com/50120304/151884348-5b1178a4-c3e4-4505-ac85-20fdb2fdedba.png">

**Comment by LeJeanbono** [comment]
@sravanireddyseelam Tell me if it's ok for you ;)
