### ISSUE TITLE
Possibility to hide authentication parameters in request headers

### ISSUE THREAD

**Issue by nicolas-tf** [bahmutov/cy-api#175]
I believe it is valid to have a way to hide authentication data as tokens passed through the header.

## For example:

![image](https://user-images.githubusercontent.com/81117784/194317797-5dbf736a-4e20-4dc8-b221-09e5732b09f4.png)

**Comment by bahmutov** [comment]
Sure, can you submit a pull request to add this?

**Comment by LeJeanbono** [comment]
Thanks for contributing :)
