### ISSUE TITLE
experimentalSessionAndOrigin dont prettify json

### ISSUE THREAD

**Issue by ChristoferRSouza** [bahmutov/cy-api#177]
when activating experimentalSessionAndOrigin dont prettify json as shown in the image

Add cypress.json
`{
	"experimentalSessionAndOrigin": true,
}`

![image](https://user-images.githubusercontent.com/100442957/198361629-7ab43123-066e-4fe3-9128-462486e2fae5.png)
![image](https://user-images.githubusercontent.com/100442957/198361674-3021e321-ffa9-43eb-9b07-38049551ba01.png)

**Comment by LeJeanbono** [comment]
Hi @ChristoferRSouza , I will take a look.
Are we ok that your problem is the formating one ?

**Comment by ChristoferRSouza** [comment]
> Hi @ChristoferRSouza , I will take a look. Are we ok that your problem is the formating one ?

Yes that's right @LeJeanbono

**Comment by LeJeanbono** [comment]
@ChristoferRSouza  can you try to add `testIsolation: false` and see if the problem is gone ?
Thanks

**Comment by LeJeanbono** [comment]
Thanks for your feedback
Happy Testing !
