### ISSUE TITLE
Requisition printing being cut on the screen

### ISSUE THREAD

**Issue by Alisson4i** [bahmutov/cy-api#179]
Hello dear

When I use cypress in version 10 the print of requisition in the screen being cut and I can't use the scroll bar to view all.

![image](https://user-images.githubusercontent.com/97967463/200920615-1e39a5fb-cb92-4d9d-a69b-f0096269c0d9.png)

**Comment by pj-alves** [comment]
Confirmed with versions 11 and 12, any news on this?

**Comment by bahmutov** [comment]
Can you make a reproducible example showing the problem, please?

**Comment by pj-alves** [comment]
As I see, for my example the issue is related with the token size.

Example:
`		cy.api({
			method: 'POST',
			url:  'https://dummy.restapiexample.com/api/v1/create',
			headers: {
				Authorization: "Bearer yy6XfnspTfoCMCNADyOb8INpcjt7ixMaTLm7hxy3b0B7CQe1SA78UseH0TNauy8SsTjXbJJRzGPEgJhABNLBz0aMDvZmfrwseMzCmoD4KZ6v4Y3aF8ifeAjBJpmetDVdxJeDRVtn9ONcCKPyp4xlwbVK4s5mVxX16xxL02AZkgi6dBmK6Ii2JhLvumygoAEghYSyOdbWSzF4rrsxee9Zh21F5Dqf3qHbSlp54o2Pr1MvHPW5kMNqdW8SoQm7yrFme3ATpSqBkv03iYutVMBsAHLe5L7Yt5ZoBdQ2j5Pxm6fgOzaqrZV9bDA1PSqAv7UC3M1JUXRUSMQ5e9ZWLbrq43wykwNJHkTVSi9XHdncWJNTNyHKVAG87SLcGgTuXp4uOmYO12zSpVRSKVg6HaDDzHdaQ3SZCyALjnKWxypZUzGY5VCNm9txNofGDIWUaLaIBBdCwzsxekmNLQl4ymuhAT50aeOSf4MsPMWWeUTQ6oIiIgKfgCWzvWfhieUHIV6NKCzhkSq5bBqpyGxldmbS0rtvmmJx5Tk0okylLNI3NvMXevBNOlWrrBvsGG8lEJ1GrJ74sfGVtGAoqvJTgsdC7dGbop2Y1aXCkoiz7qvbDDoZTYYbusDMQ3XWShqQoR8zcrKDXJDZLT6vEUtfu89a0UCdXU2LwdcQtsdTgKb4viqPU2iFNNdjprhLSeDCid8v648mhKYaX6kDnw1BrTBqlORJMGGMlSaQ9xtPNJFJaYAohg1lZ8DOUtdOo6XqiDaegmi5ovGxdqZe10UUQ734LBWU2dfm0WWx"
			},
			body : {
				'sample': 'this is a sample'
			}			
		})`

**Comment by pakhilov** [comment]
> Can you make a reproducible example showing the problem, please?

Hi, Gleb it easy to reproduce from this example tests in repo itself https://github.com/bahmutov/cy-api
Just update cypress version to latest


![Screenshot 2022-12-21 at 1 00 42 PM](https://user-images.githubusercontent.com/10390058/209002813-78ae3405-f0b3-452c-ae5b-f5ba1b4588b3.png)
![Screenshot 2022-12-21 at 12 56 58 PM](https://user-images.githubusercontent.com/10390058/209002844-d6d9626c-36c0-4043-a9ef-b3415e5649a1.png)
