### ISSUE TITLE
README Link Typo

### ISSUE THREAD

**Issue by andrew-pyle** [bahmutov/cy-api#209]
There is a typo in the URL for one of the links in the README for this project.

Line 70 is missing the "r" in "server" in `https://glebbahmutov.com/blog/api-testing-with-sever-logs/`. The link goes to a GitHub Pages 404 error.

It should be `https://glebbahmutov.com/blog/api-testing-with-server-logs/`, I think.

```
  68 |  ## More info
  69 |  
- 70 |  - Read [Black box API testing with server logs](https://glebbahmutov.com/blog/api-testing-with-sever-logs/)
+ 70 |  - Read [Black box API testing with server logs](https://glebbahmutov.com/blog/api-testing-with-server-logs/)
  71 |  - Read [Capture all the logs](https://glebbahmutov.com/blog/capture-all-the-logs/) and [@bahmutov/all-logs][all-logs] module.
  72 |  - Read [You Should Test More Using APIs](https://glebbahmutov.com/blog/test-using-apis/)
 ```

P.S. Thank you for all your writing on the Cypress ecosystem!

**Comment by LeJeanbono** [comment]
Thanks @andrew-pyle !
Happy testing !
