### ISSUE TITLE
Weird behavior when sending more than one request

### ISSUE THREAD

**Issue by jprealini** [bahmutov/cy-api#228]
I was trying to implement cy.api for an API testing suite. 

For one scenario I have let's say 3 requests that happen. The first one returns some value that the second one needs for its body. So I went something like this:
```
cy.api("Req1", () => {
  do the request
  get the response
  Cypress.env("value", response.value)
})

cy.api("Req2", () => {
  do the request using "Cypress.env("value")" in body payload
  get the response  
})
```
I noticed that the second request was failing due to "Cypress.env("value")" was undefined...  I tried different things, and then ended up changing "cy.api" for "cy.request", and magically, everything works as expected

It's as if cy.api is not waiting for the first request to complete before continuing with the second one, causing the env. varialbe to not be populated before the second request happens

Is this a known issue with cy.api? or some configuration problem? 

Thanks

**Comment by bahmutov** [comment]
Closing as resolved
