### ISSUE TITLE
Not support firefox ?

### ISSUE THREAD

**Issue by golfzaptw** [bahmutov/cy-api#54]
I found error when running with firefox

Firefox run
<img width="1440" alt="Screen Shot 2563-02-25 at 14 29 46" src="https://user-images.githubusercontent.com/21608972/75224639-6e683980-57db-11ea-9885-1a1315ff25e2.png">

Edge run
<img width="1440" alt="Screen Shot 2563-02-25 at 14 30 01" src="https://user-images.githubusercontent.com/21608972/75224658-7a53fb80-57db-11ea-8641-d257468ecd68.png">

**Comment by poponuts** [comment]
I exactly have same issue so all my tests with cy.api included are failing in Firefox. Works fine with Edge and Chrome.

**Comment by bahmutov** [comment]
yeah, I can see Firefox 72 not running it

<img width="1440" alt="Screen Shot 2020-04-01 at 12 07 58 PM" src="https://user-images.githubusercontent.com/2212006/78160112-7e45ef80-7411-11ea-9ab1-c7089f5717fb.png">

**Comment by bahmutov** [comment]
This is how the markup should look - the application's iframe should have `<div class="container">` inside
<img width="1282" alt="Screen Shot 2020-04-01 at 12 12 10 PM" src="https://user-images.githubusercontent.com/2212006/78160526-1643d900-7412-11ea-986e-69b38ddf9fb1.png">

**Comment by bahmutov** [comment]
Ok, by pausing at the start of the test, I think I understand what happens.

In Chrome, the starting blank page has our text

<img width="1282" alt="Screen Shot 2020-04-01 at 12 16 45 PM" src="https://user-images.githubusercontent.com/2212006/78161014-d2050880-7412-11ea-9ea7-9018fb505544.png">

But in Firefox, the starting page is completely empty

<img width="1440" alt="Screen Shot 2020-04-01 at 12 17 10 PM" src="https://user-images.githubusercontent.com/2212006/78161032-dc270700-7412-11ea-9e36-2a6ad505e1fd.png">

**Comment by poponuts** [comment]
Works like a charm now!
