### ISSUE TITLE
Using cy.api command in UI tests also displays API request/response

### ISSUE THREAD

**Issue by fpl1976** [bahmutov/cy-api#73]
I am trying to use the cy.api command in a base class like this:

```js  
protected post(request: ApiRequest): Cypress.Chainable<Cypress.Response> {
    return cy.api({
      method: HttpMethod.POST,
      url: this.buildUrl(request),
      failOnStatusCode: false,
      auth: this.setAuth(request.token),
      body: request.payload
    }).as(API_RESPONSE_ID);

  }
````

But I am using the same base class both for API and UI testing. 
Is there a way to hide the request/response details in the test runner?

**Comment by leosuncin** [comment]
Not a solution, just an alternative: use `cy.request` has the same params

**Comment by bahmutov** [comment]
Right now no - but if you are willing to put in time, it might be an option to `cy.api` to NOT print anything to the DOM and just perform its assertion?

**Comment by fpl1976** [comment]
That would we awesome to have and be able to use `cy.api` in all scenarios

**Comment by LeJeanbono** [comment]
Working on a Cypress option `apiDisplayRequest` that will setting `cy.api` result showing (so will have same behavior as cy.request)
```js
it('calls API without displaying request', { apiDisplayRequest: false }, () => {
    cy.api(
      {
        url: '/',
      }
    )
    cy.visit(...)
    cy.api(
      {
        url: '/',
      }
    )
})
```
Will respond to your need @fpl1976 ?

**Comment by FelixPradosFL** [comment]
yes, that would work. I like the options approach.
